In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# 1. Подберите скорость обучения (alpha) и количество итераций(к значениям, полученным методом наименьших квадратов)    

In [3]:
X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],   
              [1, 1, 2, 1, 3, 0, 5, 10, 1, 2]])
X

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  2,  1,  3,  0,  5, 10,  1,  2]])

In [4]:
y = [45, 55, 50, 59, 65, 35, 75, 80, 50, 60]
y

[45, 55, 50, 59, 65, 35, 75, 80, 50, 60]

In [5]:
w = np.linalg.inv(X @ X.T) @ X @ y
w

array([47.23214286,  3.91071429])

In [6]:
def calc_mse(y, y_pred):
    err = np.mean((y - y_pred)**2)
    return err

In [7]:
n = X.shape[1]
alpha = 1e-2
w = np.array([1, 0.5])

for i in range(2310):
    y_pred = np.dot(w, X)
    err = calc_mse(y, y_pred)
    for j in range(w.shape[0]):
        w[j] -= alpha * (1/n * 2 * np.sum(X[j] * (y_pred - y)))
    if i % 100 == 0:
        print(i, w, err)

0 [2.102 3.9  ] 3173.15
100 [31.88770806  6.74418155] 175.19445858001848
200 [41.83683774  4.90699865] 61.9177717428135
300 [45.33508261  4.26102097] 47.913169919666764
400 [46.56511152  4.03388672] 46.18175564810758
500 [46.99760587  3.95402334] 45.96769776787538
600 [47.14967657  3.92594232] 45.941233404700036
700 [47.20314662  3.91606866] 45.93796156758049
800 [47.2219474   3.91259695] 45.937557064435396
900 [47.228558    3.91137626] 45.937507054979434
1000 [47.23088237  3.91094704] 45.937500872219886
1100 [47.23169965  3.91079613] 45.937500107834126
1200 [47.23198702  3.91074306] 45.93750001333172
1300 [47.23208806  3.9107244 ] 45.93750000164824
1400 [47.23212359  3.91071784] 45.93750000020376
1500 [47.23213608  3.91071554] 45.93750000002521
1600 [47.23214048  3.91071473] 45.93750000000313
1700 [47.23214202  3.91071444] 45.937500000000384
1800 [47.23214256  3.91071434] 45.93750000000005
1900 [47.23214275  3.9107143 ] 45.93750000000001
2000 [47.23214282  3.91071429] 45.9374999999999

Ответ: альфа 1e-2, количество итераций 2300 (в коде 2310 потому что правая граница диапазона range не включается)

In [8]:
# 2. В этом коде мы избавляемся от итераций по весам, но тут есть ошибка, исправьте ее:

In [9]:
X

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  2,  1,  3,  0,  5, 10,  1,  2]])

In [10]:
y

[45, 55, 50, 59, 65, 35, 75, 80, 50, 60]

In [11]:
w = np.array([1, 0.5])

for i in range(5000):
    y_pred = np.dot(w, X)
    err = calc_mse(y, y_pred)
    '''for j in range(W.shape[0]):
        W[j] -= alpha * (1/n * 2 * np.sum(X[j] * (y_pred - y)))'''
    w -= alpha * (1/n * 2 * np.sum(X * (y_pred - y), axis=1))
    if i % 100 == 0:
        print(i, w, err)

0 [2.102 3.9  ] 3173.15
100 [31.88770806  6.74418155] 175.19445858001848
200 [41.83683774  4.90699865] 61.9177717428135
300 [45.33508261  4.26102097] 47.913169919666764
400 [46.56511152  4.03388672] 46.18175564810758
500 [46.99760587  3.95402334] 45.96769776787538
600 [47.14967657  3.92594232] 45.941233404700036
700 [47.20314662  3.91606866] 45.93796156758049
800 [47.2219474   3.91259695] 45.937557064435396
900 [47.228558    3.91137626] 45.937507054979434
1000 [47.23088237  3.91094704] 45.937500872219886
1100 [47.23169965  3.91079613] 45.937500107834126
1200 [47.23198702  3.91074306] 45.93750001333172
1300 [47.23208806  3.9107244 ] 45.93750000164824
1400 [47.23212359  3.91071784] 45.93750000020376
1500 [47.23213608  3.91071554] 45.93750000002521
1600 [47.23214048  3.91071473] 45.93750000000313
1700 [47.23214202  3.91071444] 45.937500000000384
1800 [47.23214256  3.91071434] 45.93750000000005
1900 [47.23214275  3.9107143 ] 45.93750000000001
2000 [47.23214282  3.91071429] 45.9374999999999

Ответ: нам нужно считать сумму по строкам, а в рассчете суммы отсутствовало условние axis=1. Добавила условие построчного рассчета axis=1 (не уверена, предположение)